spring:
  docker:
    compose:
      stop:
        command: down
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    org.springframework.jdbc.core: trace

datasource:
  url: ${SPRING_DATASOURCE_URL}
#  url: jdbc:postgresql://localhost:5432/auth_db
  username: auth
  password: auth